<?php

use Illuminate\Database\Seeder;

class ElptsDocsFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('elpts_docs_fields')->delete();
        
        \DB::table('elpts_docs_fields')->insert(array (
            0 => 
            array (
                'id' => 58,
                'doctypes_id' => 0,
                'templates_fields_id' => 198,
                'name' => 'Реквизиты организации',
                'alias' => 'SubjectOrgDetails',
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 25,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            1 => 
            array (
                'id' => 6,
                'doctypes_id' => 0,
                'templates_fields_id' => 160,
                'name' => 'КПП',
                'alias' => 'BusinessKPPId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'is_kpp',
                'visible' => 1,
                'enable' => 1,
                'sort' => 29,
                'parent_id' => 58,
                'required' => NULL,
            ),
            2 => 
            array (
                'id' => 24,
                'doctypes_id' => 0,
                'templates_fields_id' => 186,
            'name' => 'Свидетельство о гос регистрации ЮЛ или лист записи ЕГРЮЛ (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 250,
                'parent_id' => 73,
                'required' => NULL,
            ),
            3 => 
            array (
                'id' => 8,
                'doctypes_id' => 0,
                'templates_fields_id' => 8,
                'name' => 'WMI',
                'alias' => 'WMI',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:3|max:3|regex:/^[A-Za-z0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 90,
                'parent_id' => 58,
                'required' => NULL,
            ),
            4 => 
            array (
                'id' => 28,
                'doctypes_id' => 0,
                'templates_fields_id' => 13,
            'name' => 'Аттестат аккредитации для Оператора ТО (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 290,
                'parent_id' => 73,
                'required' => NULL,
            ),
            5 => 
            array (
                'id' => 23,
                'doctypes_id' => 0,
                'templates_fields_id' => 185,
            'name' => 'Устав (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 240,
                'parent_id' => 73,
                'required' => NULL,
            ),
            6 => 
            array (
                'id' => 54,
                'doctypes_id' => 0,
                'templates_fields_id' => 178,
                'name' => 'Индекс',
                'alias' => 'SubjectPostIndex',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:6|max:6|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 167,
                'parent_id' => 47,
                'required' => NULL,
            ),
            7 => 
            array (
                'id' => 27,
                'doctypes_id' => 0,
                'templates_fields_id' => 12,
            'name' => 'WMI для изготовителей (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 280,
                'parent_id' => 73,
                'required' => NULL,
            ),
            8 => 
            array (
                'id' => 75,
                'doctypes_id' => 2,
                'templates_fields_id' => 203,
            'name' => 'Текст заявления в свободной форме (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 275,
                'parent_id' => 73,
                'required' => NULL,
            ),
            9 => 
            array (
                'id' => 76,
                'doctypes_id' => 2,
                'templates_fields_id' => 6,
            'name' => 'ОКВЭД (через ";" без пробелов)',
                'alias' => 'BusinessOKVEDId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:2|regex:/^[0-9;.]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 80,
                'parent_id' => 58,
                'required' => NULL,
            ),
            10 => 
            array (
                'id' => 22,
                'doctypes_id' => 0,
                'templates_fields_id' => 184,
                'name' => 'Телефон',
                'alias' => 'BusinessTelephone',
                'type' => 'input',
                'link' => NULL,
                'mask' => 'phone',
                'valid_rules' => 'min:15|max:15|is_phone',
                'visible' => 1,
                'enable' => 1,
                'sort' => 230,
                'parent_id' => 57,
                'required' => NULL,
            ),
            11 => 
            array (
                'id' => 1,
                'doctypes_id' => 0,
                'templates_fields_id' => 1,
                'name' => 'Текст документа',
                'alias' => 'DogText',
                'type' => 'text',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 10,
                'parent_id' => 80,
                'required' => 1,
            ),
            12 => 
            array (
                'id' => 20,
                'doctypes_id' => 0,
                'templates_fields_id' => 209,
                'name' => 'Адрес электронной почты',
                'alias' => 'BusinessEmail',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300|email',
                'visible' => 1,
                'enable' => 1,
                'sort' => 210,
                'parent_id' => 57,
                'required' => 1,
            ),
            13 => 
            array (
                'id' => 77,
                'doctypes_id' => 0,
                'templates_fields_id' => NULL,
                'name' => 'Согласие на акцепт документа',
                'alias' => NULL,
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 0,
                'sort' => 319,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            14 => 
            array (
                'id' => 79,
                'doctypes_id' => 0,
                'templates_fields_id' => NULL,
                'name' => 'Капча',
                'alias' => NULL,
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 329,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            15 => 
            array (
                'id' => 29,
                'doctypes_id' => 0,
                'templates_fields_id' => 14,
            'name' => 'Аттестат аккредитации для испытательных лабораторий (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 300,
                'parent_id' => 73,
                'required' => NULL,
            ),
            16 => 
            array (
                'id' => 25,
                'doctypes_id' => 0,
                'templates_fields_id' => 187,
            'name' => 'Свидетельство о постановке на учет в налоговом органе (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 260,
                'parent_id' => 73,
                'required' => NULL,
            ),
            17 => 
            array (
                'id' => 30,
                'doctypes_id' => 0,
                'templates_fields_id' => 201,
                'name' => 'Согласие на акцепт документа',
                'alias' => 'AgreementText',
                'type' => 'checkbox',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 11,
                'parent_id' => 80,
                'required' => 1,
            ),
            18 => 
            array (
                'id' => 53,
                'doctypes_id' => 0,
                'templates_fields_id' => 177,
                'name' => 'Номер помещения',
                'alias' => 'SubjectSpaceNumber',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 166,
                'parent_id' => 47,
                'required' => NULL,
            ),
            19 => 
            array (
                'id' => 7,
                'doctypes_id' => 1,
                'templates_fields_id' => 6,
            'name' => 'ОКВЭД (через ";" без пробелов)',
                'alias' => 'BusinessOKVEDId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:2|regex:/^[0-9;.]+$/|is_okved_exists',
                'visible' => 1,
                'enable' => 1,
                'sort' => 80,
                'parent_id' => 58,
                'required' => NULL,
            ),
            20 => 
            array (
                'id' => 81,
                'doctypes_id' => 2,
                'templates_fields_id' => 204,
                'name' => 'Номер акцепта Оферты',
                'alias' => 'ContractId',
                'type' => 'select',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 5,
                'parent_id' => 80,
                'required' => NULL,
            ),
            21 => 
            array (
                'id' => 51,
                'doctypes_id' => 0,
                'templates_fields_id' => 175,
                'name' => 'Улица',
                'alias' => 'SubjectStreet',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 164,
                'parent_id' => 47,
                'required' => NULL,
            ),
            22 => 
            array (
                'id' => 10,
                'doctypes_id' => 0,
                'templates_fields_id' => 162,
                'name' => 'Номер в едином реестре',
                'alias' => 'UnifiedRegId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:3|max:3|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 110,
                'parent_id' => 58,
                'required' => NULL,
            ),
            23 => 
            array (
                'id' => 21,
                'doctypes_id' => 0,
                'templates_fields_id' => 210,
                'name' => 'Код подтверждения',
                'alias' => NULL,
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 220,
                'parent_id' => 57,
                'required' => 1,
            ),
            24 => 
            array (
                'id' => 11,
                'doctypes_id' => 0,
                'templates_fields_id' => 10,
                'name' => 'Номер в гос. реестре ломбардов',
                'alias' => 'LombardId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 120,
                'parent_id' => 58,
                'required' => NULL,
            ),
            25 => 
            array (
                'id' => 4,
                'doctypes_id' => 0,
                'templates_fields_id' => 159,
                'name' => 'ИНН',
                'alias' => 'BusinessINNId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'is_inn',
                'visible' => 1,
                'enable' => 1,
                'sort' => 26,
                'parent_id' => 58,
                'required' => NULL,
            ),
            26 => 
            array (
                'id' => 43,
                'doctypes_id' => 0,
                'templates_fields_id' => 164,
                'name' => 'Номер регистрации в реестре ОТО',
                'alias' => 'RegistryOTOId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 121,
                'parent_id' => 58,
                'required' => NULL,
            ),
            27 => 
            array (
                'id' => 36,
                'doctypes_id' => 2,
                'templates_fields_id' => 16,
                'name' => 'СНИЛС',
                'alias' => 'SNILS',
                'type' => 'input',
                'link' => NULL,
                'mask' => 'snils',
                'valid_rules' => 'is_snils',
                'visible' => 1,
                'enable' => 1,
                'sort' => 28,
                'parent_id' => 58,
                'required' => NULL,
            ),
            28 => 
            array (
                'id' => 82,
                'doctypes_id' => 1,
                'templates_fields_id' => 213,
                'name' => 'Марка организации-изготовителя, чья продукция реализуется',
                'alias' => 'OrgMake',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 81,
                'parent_id' => 58,
                'required' => NULL,
            ),
            29 => 
            array (
                'id' => 47,
                'doctypes_id' => 0,
                'templates_fields_id' => 191,
                'name' => 'Адрес местонахождения',
                'alias' => 'SubjectAddressDetails',
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 145,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            30 => 
            array (
                'id' => 12,
                'doctypes_id' => 0,
                'templates_fields_id' => 168,
                'name' => 'Должность',
                'alias' => 'BusinessOccupationName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 130,
                'parent_id' => 58,
                'required' => NULL,
            ),
            31 => 
            array (
                'id' => 48,
                'doctypes_id' => 0,
                'templates_fields_id' => 172,
                'name' => 'Район',
                'alias' => 'SubjectDistrict',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 161,
                'parent_id' => 47,
                'required' => NULL,
            ),
            32 => 
            array (
                'id' => 49,
                'doctypes_id' => 0,
                'templates_fields_id' => 173,
                'name' => 'Город',
                'alias' => 'SubjectCity',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 162,
                'parent_id' => 47,
                'required' => NULL,
            ),
            33 => 
            array (
                'id' => 14,
                'doctypes_id' => 0,
                'templates_fields_id' => 170,
                'name' => 'Страна',
                'alias' => 'CountryName',
                'type' => 'select',
                'link' => 'countries',
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 150,
                'parent_id' => 47,
                'required' => NULL,
            ),
            34 => 
            array (
                'id' => 41,
                'doctypes_id' => 0,
                'templates_fields_id' => 156,
                'name' => 'Краткое наименование организации',
                'alias' => 'BusinessEntityShortName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 35,
                'parent_id' => 58,
                'required' => NULL,
            ),
            35 => 
            array (
                'id' => 52,
                'doctypes_id' => 0,
                'templates_fields_id' => 176,
                'name' => 'Дом',
                'alias' => 'SubjectHouse',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 165,
                'parent_id' => 47,
                'required' => NULL,
            ),
            36 => 
            array (
                'id' => 16,
                'doctypes_id' => 0,
                'templates_fields_id' => 179,
                'name' => 'Наименование банка',
                'alias' => 'BankName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 170,
                'parent_id' => 55,
                'required' => NULL,
            ),
            37 => 
            array (
                'id' => 42,
                'doctypes_id' => 0,
                'templates_fields_id' => 161,
                'name' => 'Корреспондентский счет',
                'alias' => 'CorrespondentAccount',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 105,
                'parent_id' => 58,
                'required' => NULL,
            ),
            38 => 
            array (
                'id' => 44,
                'doctypes_id' => 0,
                'templates_fields_id' => 165,
                'name' => 'Номер аттестата',
                'alias' => 'CertificateId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20',
                'visible' => 1,
                'enable' => 1,
                'sort' => 122,
                'parent_id' => 58,
                'required' => NULL,
            ),
            39 => 
            array (
                'id' => 45,
                'doctypes_id' => 0,
                'templates_fields_id' => 166,
                'name' => 'Полное наименование органа по сертификации/испытательной лаборатории',
                'alias' => 'CertLabName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 123,
                'parent_id' => 58,
                'required' => NULL,
            ),
            40 => 
            array (
                'id' => 46,
                'doctypes_id' => 0,
                'templates_fields_id' => 167,
                'name' => 'Краткое наименование органа по сертификации/испытательной лаборатории',
                'alias' => 'CertLabShortName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 124,
                'parent_id' => 58,
                'required' => NULL,
            ),
            41 => 
            array (
                'id' => 17,
                'doctypes_id' => 0,
                'templates_fields_id' => 181,
                'name' => 'БИК банка',
                'alias' => 'BankBIKid',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:9|max:9|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 180,
                'parent_id' => 55,
                'required' => NULL,
            ),
            42 => 
            array (
                'id' => 18,
                'doctypes_id' => 0,
                'templates_fields_id' => 182,
                'name' => 'Корреспонденский счет',
                'alias' => 'CorrespondentAccount',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 190,
                'parent_id' => 55,
                'required' => NULL,
            ),
            43 => 
            array (
                'id' => 19,
                'doctypes_id' => 0,
                'templates_fields_id' => 183,
                'name' => 'Расчетный счет',
                'alias' => 'PaymentAccount',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:20|max:20|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 200,
                'parent_id' => 55,
                'required' => NULL,
            ),
            44 => 
            array (
                'id' => 55,
                'doctypes_id' => 0,
                'templates_fields_id' => 192,
                'name' => 'Банковские реквизиты',
                'alias' => 'SubjectBankDetails',
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 168,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            45 => 
            array (
                'id' => 3,
                'doctypes_id' => 0,
                'templates_fields_id' => 158,
                'name' => 'Организационно-правовая форма',
                'alias' => 'BusinessEntityTypeName',
                'type' => 'select',
                'link' => 'okopfs',
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 40,
                'parent_id' => 58,
                'required' => NULL,
            ),
            46 => 
            array (
                'id' => 9,
                'doctypes_id' => 0,
                'templates_fields_id' => 9,
                'name' => 'БИК',
                'alias' => 'BikID',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:9|max:9|regex:/^[0-9]+$/',
                'visible' => 1,
                'enable' => 1,
                'sort' => 100,
                'parent_id' => 58,
                'required' => NULL,
            ),
            47 => 
            array (
                'id' => 56,
                'doctypes_id' => 0,
                'templates_fields_id' => 180,
                'name' => 'Местонахождение банка',
                'alias' => 'BankAddress',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 175,
                'parent_id' => 55,
                'required' => NULL,
            ),
            48 => 
            array (
                'id' => 57,
                'doctypes_id' => 0,
                'templates_fields_id' => 193,
                'name' => 'Контактные данные',
                'alias' => 'UnifiedCommunicationDetails',
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 205,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            49 => 
            array (
                'id' => 62,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Наличие в специализированных реестрах',
                'alias' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 500,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            50 => 
            array (
                'id' => 63,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Сведения о ликвидации, реорганизации, уменьшении уставного капитала, исключении из ЕГРЮЛ',
                'alias' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 510,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            51 => 
            array (
                'id' => 64,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
            'name' => 'Сведения о несостоятельности (банкротстве) в базе данных арбитражных судов, в базе данных публикаций о банкротстве / сведения о залоге',
                'alias' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 520,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            52 => 
            array (
                'id' => 65,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Полномочия исполнительного органа по Уставу',
                'alias' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 530,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            53 => 
            array (
                'id' => 66,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Оплата',
                'alias' => NULL,
                'type' => 'select',
                'link' => 'pays',
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 540,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            54 => 
            array (
                'id' => 67,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Утиль',
                'alias' => NULL,
                'type' => 'select',
                'link' => 'junks',
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 550,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            55 => 
            array (
                'id' => 68,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Название тарифного плана',
                'alias' => NULL,
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 560,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            56 => 
            array (
                'id' => 69,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Собственник',
                'alias' => NULL,
                'type' => 'select',
                'link' => 'owners',
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 570,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            57 => 
            array (
                'id' => 70,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Годовой объем выпуска/план',
                'alias' => NULL,
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 580,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            58 => 
            array (
                'id' => 71,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Годовой объем выручки',
                'alias' => NULL,
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 590,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            59 => 
            array (
                'id' => 72,
                'doctypes_id' => 1,
                'templates_fields_id' => NULL,
                'name' => 'Статус в АС СЭП',
                'alias' => NULL,
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 0,
                'enable' => 1,
                'sort' => 600,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            60 => 
            array (
                'id' => 73,
                'doctypes_id' => 0,
                'templates_fields_id' => 194,
                'name' => 'Приложение документов',
                'alias' => NULL,
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 235,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            61 => 
            array (
                'id' => 74,
                'doctypes_id' => 0,
                'templates_fields_id' => 154,
                'name' => 'Полное наименование организации',
                'alias' => 'BusinessEntityName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 30,
                'parent_id' => 58,
                'required' => NULL,
            ),
            62 => 
            array (
                'id' => 5,
                'doctypes_id' => 0,
                'templates_fields_id' => 212,
                'name' => 'ОГРН/ОГРНИП',
                'alias' => 'BusinessOGRNId',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'is_ogrn',
                'visible' => 1,
                'enable' => 1,
                'sort' => 27,
                'parent_id' => 58,
                'required' => 1,
            ),
            63 => 
            array (
                'id' => 83,
                'doctypes_id' => 1,
                'templates_fields_id' => 214,
                'name' => 'Объем выпущенных/проданных/переданных в лизинг автомобилей в месяц/год',
                'alias' => 'CarVolume',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 82,
                'parent_id' => 58,
                'required' => NULL,
            ),
            64 => 
            array (
                'id' => 78,
                'doctypes_id' => 0,
                'templates_fields_id' => NULL,
                'name' => 'Сертификат ЭЦП',
                'alias' => NULL,
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 309,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            65 => 
            array (
                'id' => 60,
                'doctypes_id' => 0,
                'templates_fields_id' => 195,
                'name' => 'Капча',
                'alias' => NULL,
                'type' => 'captcha',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'captcha',
                'visible' => 1,
                'enable' => 1,
                'sort' => 330,
                'parent_id' => 79,
                'required' => NULL,
            ),
            66 => 
            array (
                'id' => 13,
                'doctypes_id' => 0,
                'templates_fields_id' => 169,
            'name' => 'Фамилия, Имя, Отчество (при наличии)',
                'alias' => 'BusinessСhiefName',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:300',
                'visible' => 1,
                'enable' => 1,
                'sort' => 140,
                'parent_id' => 58,
                'required' => NULL,
            ),
            67 => 
            array (
                'id' => 15,
                'doctypes_id' => 0,
                'templates_fields_id' => 171,
                'name' => 'Субъект',
                'alias' => 'SubjectArea',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 160,
                'parent_id' => 47,
                'required' => NULL,
            ),
            68 => 
            array (
                'id' => 50,
                'doctypes_id' => 0,
                'templates_fields_id' => 174,
                'name' => 'Населенный пункт',
                'alias' => 'SubjectVillage',
                'type' => 'input',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'min:1|max:500',
                'visible' => 1,
                'enable' => 1,
                'sort' => 163,
                'parent_id' => 47,
                'required' => NULL,
            ),
            69 => 
            array (
                'id' => 26,
                'doctypes_id' => 0,
                'templates_fields_id' => 188,
            'name' => 'Документ, подтверждающий полномочия лица на осуществление действий от имени юр лица без доверенности (копия решения или протокола о назначении или избрании руководителя организации, действующее на момент заключения договора) (pdf)',
                'alias' => NULL,
                'type' => 'file',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'mimes:pdf|max:5120',
                'visible' => 1,
                'enable' => 1,
                'sort' => 270,
                'parent_id' => 73,
                'required' => NULL,
            ),
            70 => 
            array (
                'id' => 80,
                'doctypes_id' => 0,
                'templates_fields_id' => NULL,
                'name' => 'Реквизиты документа',
                'alias' => 'SubjectDetails',
                'type' => 'header',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => NULL,
                'visible' => 1,
                'enable' => 1,
                'sort' => 1,
                'parent_id' => NULL,
                'required' => NULL,
            ),
            71 => 
            array (
                'id' => 61,
                'doctypes_id' => 0,
                'templates_fields_id' => 211,
                'name' => 'Выбор сертификата',
                'alias' => NULL,
                'type' => 'certificate',
                'link' => NULL,
                'mask' => NULL,
                'valid_rules' => 'certificate',
                'visible' => 1,
                'enable' => 1,
                'sort' => 310,
                'parent_id' => 78,
                'required' => NULL,
            ),
        ));
        
        
    }
}