<?php

use Illuminate\Database\Seeder;

class ElptsTemplatesFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('elpts_templates_fields')->delete();
        
        \DB::table('elpts_templates_fields')->insert(array (
            0 => 
            array (
                'id' => 7,
                'doctypes_id' => 1,
                'parent_id' => 198,
                'name' => 'Список номеров ОКВЭД для проверки',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 214,
                'valid_rules' => 'nullable|min:2|regex:/^[0-9;.]+$/',
                'visible' => 1,
            ),
            1 => 
            array (
                'id' => 198,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Реквизиты организации',
                'short_name' => 'Реквизиты',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 160,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'doctypes_id' => 0,
                'parent_id' => 206,
                'name' => 'Текст письма о принятии документа на соглсование',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => 1,
                'enable' => 1,
                'sort' => 120,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            3 => 
            array (
                'id' => 5,
                'doctypes_id' => 0,
                'parent_id' => 206,
                'name' => 'Текст письма в случае несогласования документа',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => 1,
                'enable' => 1,
                'sort' => 140,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            4 => 
            array (
                'id' => 8,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'WMI',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 230,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            5 => 
            array (
                'id' => 9,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'БИК',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 240,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            6 => 
            array (
                'id' => 10,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => '№ в гос. реестре ломбардов',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 256,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            7 => 
            array (
                'id' => 12,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'WMI для изготовителей',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 530,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            8 => 
            array (
                'id' => 13,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Аттестат аккредитации для Оператора ТО',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 540,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            9 => 
            array (
                'id' => 14,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Аттестат аккредитации для испытательных лабораторий',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 550,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            10 => 
            array (
                'id' => 16,
                'doctypes_id' => 2,
                'parent_id' => 198,
                'name' => 'СНИЛС',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 700,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            11 => 
            array (
                'id' => 154,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Полное наименование организации',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 170,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            12 => 
            array (
                'id' => 156,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Краткое наименование организации',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 180,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            13 => 
            array (
                'id' => 158,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Организационно-правовая форма',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 190,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            14 => 
            array (
                'id' => 159,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'ИНН',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 200,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            15 => 
            array (
                'id' => 160,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'КПП',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 210,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            16 => 
            array (
                'id' => 161,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Корреспондентский счет',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 250,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            17 => 
            array (
                'id' => 162,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => '№ в едином реестре',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 260,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            18 => 
            array (
                'id' => 164,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => '№ регистрации в реестре ОТО',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 280,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            19 => 
            array (
                'id' => 165,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Номер аттестата',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 290,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            20 => 
            array (
                'id' => 168,
                'doctypes_id' => 0,
                'parent_id' => 190,
                'name' => 'Должность',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 320,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            21 => 
            array (
                'id' => 170,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Страна',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 340,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            22 => 
            array (
                'id' => 211,
                'doctypes_id' => 0,
                'parent_id' => 199,
                'name' => 'Сертификат ЭЦП',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 565,
                'valid_rules' => NULL,
                'visible' => 0,
            ),
            23 => 
            array (
                'id' => 210,
                'doctypes_id' => 0,
                'parent_id' => 193,
                'name' => 'Код подтверждения',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 483,
                'valid_rules' => NULL,
                'visible' => 0,
            ),
            24 => 
            array (
                'id' => 209,
                'doctypes_id' => 0,
                'parent_id' => 193,
                'name' => 'Адресс электронной почты',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 482,
                'valid_rules' => NULL,
                'visible' => 0,
            ),
            25 => 
            array (
                'id' => 204,
                'doctypes_id' => 2,
                'parent_id' => 199,
                'name' => 'Номер акцепта Оферты',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 216,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            26 => 
            array (
                'id' => 205,
                'doctypes_id' => 2,
                'parent_id' => 199,
                'name' => 'Список префиксов Оферты для проверки',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 217,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            27 => 
            array (
                'id' => 1,
                'doctypes_id' => 0,
                'parent_id' => 207,
                'name' => 'Текст документа',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => 1,
                'enable' => 1,
                'sort' => 100,
                'valid_rules' => 'min:1',
                'visible' => 1,
            ),
            28 => 
            array (
                'id' => 201,
                'doctypes_id' => 0,
                'parent_id' => 199,
                'name' => 'Текст чек-бокса акцепта документа',
                'short_name' => NULL,
                'type' => 'input',
                'link' => NULL,
                'required' => 1,
                'enable' => 1,
                'sort' => 102,
                'valid_rules' => 'min:1',
                'visible' => 1,
            ),
            29 => 
            array (
                'id' => 192,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Банковские реквизиты',
                'short_name' => 'Банк',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 425,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            30 => 
            array (
                'id' => 197,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Права доступа',
                'short_name' => 'Права доступа',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 600,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            31 => 
            array (
                'id' => 203,
                'doctypes_id' => 2,
                'parent_id' => 194,
                'name' => 'Текст заявления в свободной форме',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 525,
                'valid_rules' => 'min:1',
                'visible' => 1,
            ),
            32 => 
            array (
                'id' => 6,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'ОКВЭД',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 213,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            33 => 
            array (
                'id' => 182,
                'doctypes_id' => 0,
                'parent_id' => 192,
                'name' => 'Корреспонденский счет',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 460,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            34 => 
            array (
                'id' => 183,
                'doctypes_id' => 0,
                'parent_id' => 192,
                'name' => 'Расчетный счет',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 470,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            35 => 
            array (
                'id' => 184,
                'doctypes_id' => 0,
                'parent_id' => 193,
                'name' => 'Телефон',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 480,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            36 => 
            array (
                'id' => 185,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Устав',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 490,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            37 => 
            array (
                'id' => 186,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Свидетельство о гос регистрации ЮЛ или лист записи ЕГРЮЛ',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 500,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            38 => 
            array (
                'id' => 190,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Руководитель организации',
                'short_name' => 'Руководитель',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 315,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            39 => 
            array (
                'id' => 166,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Полное наименование органа по сертификации/испытательной лаборатории',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 300,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            40 => 
            array (
                'id' => 167,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'Краткое наименование органа по сертификации/испытательной лаборатории',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 310,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            41 => 
            array (
                'id' => 169,
                'doctypes_id' => 0,
                'parent_id' => 190,
            'name' => 'Фамилия, Имя, Отчество (при наличии)',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 330,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            42 => 
            array (
                'id' => 171,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Субъект',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 350,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            43 => 
            array (
                'id' => 172,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Район',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 360,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            44 => 
            array (
                'id' => 173,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Город',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 370,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            45 => 
            array (
                'id' => 174,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Населенный пункт',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 380,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            46 => 
            array (
                'id' => 175,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Улица',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 390,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            47 => 
            array (
                'id' => 176,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Дом',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 400,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            48 => 
            array (
                'id' => 177,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Номер помещения',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 410,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            49 => 
            array (
                'id' => 178,
                'doctypes_id' => 0,
                'parent_id' => 191,
                'name' => 'Индекс',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 420,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            50 => 
            array (
                'id' => 179,
                'doctypes_id' => 0,
                'parent_id' => 192,
                'name' => 'Наименование банка',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 430,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            51 => 
            array (
                'id' => 180,
                'doctypes_id' => 0,
                'parent_id' => 192,
                'name' => 'Местонахождение банка',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 440,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            52 => 
            array (
                'id' => 181,
                'doctypes_id' => 0,
                'parent_id' => 192,
                'name' => 'БИК банка',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 450,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            53 => 
            array (
                'id' => 187,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Свидетельство о постановке на учет в налоговом органе',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 510,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            54 => 
            array (
                'id' => 191,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Адрес местонахождения',
                'short_name' => 'Адрес',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 335,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            55 => 
            array (
                'id' => 193,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Контактные данные',
                'short_name' => 'Контакты',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 475,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            56 => 
            array (
                'id' => 194,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Приложение документов',
                'short_name' => 'Документы',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 485,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            57 => 
            array (
                'id' => 188,
                'doctypes_id' => 0,
                'parent_id' => 194,
                'name' => 'Документ, подтверждающий полномочия лица на осуществление действий от имени юр лица без доверенности',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 520,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            58 => 
            array (
                'id' => 4,
                'doctypes_id' => 0,
                'parent_id' => 206,
                'name' => 'Текст письма в случае согласования документа',
                'short_name' => NULL,
                'type' => 'textarea',
                'link' => NULL,
                'required' => 1,
                'enable' => 1,
                'sort' => 130,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            59 => 
            array (
                'id' => 195,
                'doctypes_id' => 0,
                'parent_id' => 199,
                'name' => 'Капча',
                'short_name' => NULL,
                'type' => 'captcha',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 560,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            60 => 
            array (
                'id' => 206,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Шаблоны писем',
                'short_name' => 'Шаблоны писем',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 590,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            61 => 
            array (
                'id' => 207,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Документ',
                'short_name' => 'Документ',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 80,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            62 => 
            array (
                'id' => 199,
                'doctypes_id' => 0,
                'parent_id' => 0,
                'name' => 'Настройки',
                'short_name' => 'Настройки',
                'type' => 'header',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 610,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            63 => 
            array (
                'id' => 15,
                'doctypes_id' => 0,
                'parent_id' => 199,
                'name' => 'Префикс к номеру документа',
                'short_name' => NULL,
                'type' => 'select',
                'link' => 'prefixes',
                'required' => 1,
                'enable' => 1,
                'sort' => 105,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            64 => 
            array (
                'id' => 212,
                'doctypes_id' => 0,
                'parent_id' => 198,
                'name' => 'ОГРН/ОГРНИП',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 205,
                'valid_rules' => NULL,
                'visible' => 0,
            ),
            65 => 
            array (
                'id' => 213,
                'doctypes_id' => 1,
                'parent_id' => 198,
                'name' => 'Марка организации-изготовителя, чья продукция реализуется',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 218,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
            66 => 
            array (
                'id' => 214,
                'doctypes_id' => 1,
                'parent_id' => 198,
                'name' => 'Объем выпущенных/проданных/переданных в лизинг автомобилей в месяц/год',
                'short_name' => NULL,
                'type' => 'checkbox',
                'link' => NULL,
                'required' => NULL,
                'enable' => 1,
                'sort' => 219,
                'valid_rules' => NULL,
                'visible' => 1,
            ),
        ));
        
        
    }
}